
name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
        id: go

      - name: Check out
        uses: actions/checkout@v2

      - name: go fmt
        run: "! go fmt ./... 2>&1 | read"

      - name: go vet
        run: go vet -mod=vendor ./...

      - name: Build
        run: go build -v -mod=vendor .

      - name: Test
        run: go test -race -cover -v -mod=vendor ./...